import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import ThemeRegistry from '@/components/Theme/ThemeRegistry'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html 
      lang="pt-br"
    >
      <body>
        <ThemeRegistry>
          <AppRouterCacheProvider
            options={{ enableCssLayer: true}}
          >
            {children}
          </AppRouterCacheProvider>
        </ThemeRegistry>
      </body>
    </html>
  )
}
